# Generated by Django 2.2.7 on 2020-01-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contect', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
