# Generated by Django 2.2.7 on 2020-01-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20200116_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img_tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='contect',
            field=models.CharField(max_length=180),
        ),
    ]
