# Generated by Django 2.2.7 on 2020-01-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_auto_20200116_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='contect',
            new_name='content',
        ),
    ]
