# Generated by Django 2.2.7 on 2020-01-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_auto_20200116_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-created_at',)},
        ),
    ]
